version: 2.1

commands:
  run_test:
    description: "Run test"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-composer-{{ checksum "composer.json" }}
      - run:
          name: Install php extensions
          command: |
            sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
            sudo docker-php-ext-install pcntl pdo_mysql
      - run:
          name: Install composer packages
          command: |
            composer install
      - save_cache:
          key: dependency-cache-composer-{{ checksum "composer.json" }}
          paths:
            - ~/app/vendor
      - run:
          name: Do static analysis
          command: |
            vendor/bin/phpstan
      - run:
          name: Test
          command: |
            vendor/bin/phpunit -d memory_limit=386M

jobs:
  run_test:
    working_directory: ~/app
    docker:
      - image: circleci/php:7.4.3
    steps:
      - run_test

workflows:
  version: 2
  build-deploy:
    jobs:
      - run_test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
